# Config file for Air in TOML format

root = "."
tmp_dir = "tmp"

[build]
# Binary file yields from `go build`
bin = "./tmp/pixie-core"
# Command to build the application
cmd = "cd core && go build -o ../tmp/pixie-core ."
# Binary file yielded from `go build`.
full_bin = "./tmp/pixie-core"
# Watch these directories for changes
include_dir = ["core"]
# List of files to watch for changes
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these directories
exclude_dir = ["core/vendor", "core/tmp", "core/.git"]
# Ignore these files
exclude_file = []
# Exclude unchanged files
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log level parameter
log = "info"
# Stop running old binary when build errors occur
stop_on_error = true
# Send interrupt signal before killing process (goroutines can finish)
send_interrupt = false
# Delay after interrupt signal sent before killing process (s)
kill_delay = 500
# Binary args passed to binary
args_bin = []

[log]
# Show log timestamp
time = false

[color]
# Customize each part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
